language: java
jdk:
  - oraclejdk8
  
install:
  - mvn install -Dmaven.test.skip=true
  
deploy:
  provider: releases
  api_key: ${api_key}
  file: "./target/blog.war"
  skip_cleanup: true
  on:
    #all_branches: true
     tags: true
  
notifications:
  email:
    - teaho2015@gmail.com
