language: java
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
deploy:
  provider: releases
  api_key: "${api_key}"
  file: "./target/blog.war"
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email:
  - teaho2015@gmail.com
  #before_install: #one way to link server test
  #- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  #  -in travis.enc -out travis -d
before_install:
 #- sed -i "s/jdbc\.url=.*/${jdbc_url}/g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.username=.*/${jdbc_username}/g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.password=.*/${jdbc_password}/g" src/main/resources/properties/jdbc.properties
env:
  global:
addons:
  apt:
    packages:
    - sshpass
  ssh_known_hosts:
  - 45.32.76.154
after_success:
- cat ~/.ssh/known_hosts
- export SSHPASS=$DEPLOY_PASS
#- sshpass -e ssh -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "sh /home/lauchapps/test.sh"
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "sh /home/lauchapps/test.sh"
- sshpass -e scp -vvv -o stricthostkeychecking=no ./target/blog.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "sh $DEPLOY_PATH/blog/blog_deploy.sh"
