language: java
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
deploy:
  provider: releases
  api_key: "${api_key}"
  file: "./target/blog.war"
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email:
  - teaho2015@gmail.com
  #before_install: #one way to link server test
  #- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  #  -in travis.enc -out travis -d
before_install:
 #- sed -i "s/jdbc\.url=.*/${jdbc_url}/g" src/main/resources/properties/jdbc.properties
 #- sed -i "s/jdbc\.username=.*/${jdbc_username}/g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.password=.*/${jdbc_password}/g" src/main/resources/properties/jdbc.properties
env:
  global:
  - secure: vWxG7pEsaCvKnGkDsHCFd0GVUHFgaqorGFiYVI85YKfeRFwAcJAs2l/PCtE8g/8XJp9sMseUh75HHlFjWG8+e0FKN18URYYwrLecFT9JHVVTYepgEXKVXsSGfz3oL6Tu7WBaQtpTvI6ywh0OCVbYtZPmuMBzq4zUjUUUEcU+tyfYkMsqXcqYMRbt8Pb7SonUIyNLCv5oYe2A76n3VaKX5V5i3CdBUfU5/ALj2ee0RZBdFRpoez8Vw/VElrNqN42My3+XhTapkvjeNCne5JrCnDUignfmebFZvDl/s5URSNrhkmo+c2BkkoAzSMz0jYxucljTfhfqKNeJkbruHXoW7PNwEmyZ/oG4FVcVJ6Nopje8KYLdTTOdao+AMmgsbzL9a+PPMLNKx8klyLzQ0lxP8t2exe1kOiPYSzideeTn/8mOEpd2F7uBDYfi9N47A2/1jtN0m1bHmMiBlkzkiqNLRoE5hevwvsw7Gyu6BPmTV0EMoA5zMPbUo2M2AK+Oe1oxwPC7L+OmTWOetsXHfGO/oUPAMpOYg1KTN+3lB7XklSa4wl9PKZW8dkq6+iQ2gWJSMyiF1dBFfc9bVy+BHex/xcz8CRN/ByThAQ7f8Yuy02NSpv+nJACp+7+6eFJvp/J9YT/qd8ZJQiP4gCzDVRrotbKIvcQaKLiEFNGjFM+uU7I=
  - secure: IvjZZDblPSdmEKpNt5eMz4voA40WKTbL0gQMZFtZkZ5nNGD52cML31aQGE1Pyghvil63vg2fGtcmE6wYhXoOiUWebjXpl7RVOS0FhFDKJx1TVtj1Gtz1UE/tWwqdvMj7PNXUo8iyFLgOL5jQLs3sod7rgtyyGsNXuCDGkFRXvb19Bp69J00Kogb1rHvG5rxtVGoW69j37TGIHfoMw7joYGP+8x4hn0BH+zBAdwEAWnjvC4zC4KRAeUGufR7G5dW0Rf8/4aRBL2fLQb2WjaUz8IN2D+hRC/QR9yfWU5QSyHRCoMPcXx3xeWIryW9d3tLEBLci07r/K5z4MSIBL63ZIarK1q1bilFf5F1ysPYHpQ1nYjZB1Yz4NvQSb9tBs5we6jW8RO+tZYqZL20pBg62ZS7+cfGsEbvgsp9WLVdb6ORESYpSLsxGOOEi/hYDRZRkOdgfYaz5uWhfnYKqHdsnOd4Uc9T/LdR1SIPEbBFHmGbF6XGiFD0jqOaGMlzquS6gwvxnC+2Hd9ybvptpE2lbf46sW17oy0EsVpMhHM6KxYmSAfqBa40rDM4BKPH0l1DPADAeNETzeGMmgUSy6fnF8IQYT9XSZforWGocteivPlrkNWG9n6NyEYoz7ova3fMNIHnaehZyOFb9e9DnHWyhfbtu0qgBICo5/2ojnkQXj8M=
  - secure: NisZ8v3wOZff4nERBvvg2yU0Pm8EUSOfmiy0baXCKqUVGJ442AGOuG/VGGl8SgPY3RxQneI+kE43PNxTGBsyy4rFn6Z/lkKlapP/zdt/dhFGK5cSlWCkaG0dvtYKTJ7A0T1ig000ejZ7atkH3hpcNBsc5lm2a1/uO0foUbjwarF6cPdcU1w444stnJpk1vewFpocAmYAUu3cQKAPSCez3Sjw9EC9jWh2tZVRJAS53rpnEXwLP9tC3GRqIe+gyN7Kv8bieBCtsRbmlvkxGuxyHgh33b9eILcEMO2hCxIoyleEty59E03n2Ep7Fa28KSA3t9pP9+D4T57BWcZl5QQE9qPN60dfP1MpOibOsxGiFsuOVRckTEIZAu0l/pGafnYANSKeQmdoo41YN+bchGkBw/B7fEC/Kgay09463D3IqEh/6uDSLKrquUEe9EDxNm6Ck1AAM0GcYrJ8LSe4VYXZBu1/BwJiww2R5YGdTmlMXX8Fx72W5lXgGI4WHwyIzmYH0kqM7n+5FpfITAVocE47DpqtmEMxWoKw3bSGb4P7kOzkOskFRZgY1NzTpFJM/HCovxGr5mZwyzG6F49XGoichtAv6bOC4MYIki8zroOwv/MmHSIKk1yiX8Gbqj7ThUWXKk5ES9YqakWWSKvtvPsRMAaFOzknLofWLMdb0OnZVUw=
  - secure: hb+I0RxuxNnD2LBS6F6Us12WxVAoU6puA5nrfwIG1VTmo8JS2TuodQhi3A9u5W4YVeSLaErzNxfxM95+kB7E5nexD3f4QT1pjshVZkw/W3MLDCYTlBsZYA39e8nUorGXlTGZZ0iM9bpWp6RzCZQ6cNtr75TgGbrV4n8z/BDUB46pMQRVpUXZFuj+nQ5dr/nRdEzt38wUm6ipSTAynuNxPhCaMQn9Iqfwp/iU219ZoLtTKDcQMc2QRm7MRbrI1uqBkZfXToMFYKf5QezNDCU/Po+2WbMeTZYW5+7HkDhEdpmKCPM9GAHeRchZHjJlHR8C6nGU82p9GcoyM+9ZopjE4UGHE+S7k60B8eUK2cZG8n3yHnipt4VkO+R929Qt5beVKU3ywAOcLnX851jW69vnqdl1MWYnYVadIVutbC7upGdJ4+k3eO/4R2W0KXK939ACr0wVy42xGazfWOCANpSkPHm+umzhOLbI0W0aPDujseAJCr7FMuV+ddQzpimZwTauO2ft98kJY1zZVEY8pFz7exBnjkflBNSmuuYjHuAfptb4ItNg0/Ys0Wv/r0UeV5tm72q9b2L2asj0QFcDDXEC7XzS29xZpUZKya95wDj3UIfmc9WrYYtQez5yaF1UzpyASle3jDrH90Hp7K6Oe7XaP07QQOIAi/NCqsohbVsa86s=
addons:
  apt:
    packages:
    - sshpass
after_success:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no target/blog.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -p "$SSHPASS" ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST  $DEPLOY_PATH/blog/blog_deploy.sh
