language: java
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.test.skip=true javadoc.skip=true
deploy:
  provider: releases
  api_key: "${api_key}"
  file: "./target/blog.war"
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email:
  - teaho2015@gmail.com
#before_install: #one way to link server test
#- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
#  -in travis.enc -out travis -d
before_install:
  - sed -i "s/jdbc\.url=.*/${jdbc_url}/g" src/main/resources/properties/jdbc.properties
  - sed -i "s/jdbc\.username=.*/${jdbc_username}/g" src/main/resources/properties/jdbc.properties
  - sed -i "s/jdbc\.password=.*/${jdbc_password}/g" src/main/resources/properties/jdbc.properties
env:
  global:
  - secure: hoiIoLjz2XxEyIv+4N1rjO9MOko2WIn8ndPfSiC+eHaXdCq7n91/qdTPVpVXF97xuVp6E4Xs0sk3L2NrUecyYbcOEne2lgV31Gi92EXN2T5ZBAwwxmVA1pREo3gSTtQp2YEFMhOka7DDfcC8Ivga3kAgsgnpbifsQ4sH7FXtyzA8jk99qfR/7Khnmz2IgJcr7iEmwRGtgWgE6+xIhqojg5lfWUE9VJzdhLcx2qti+RE4eKItYNQ885jvxzBc2XsQnTIh5BKHMZidVRoQogFPZqPdNWwGDnTXCYxJiKkrAMfg/xBbIk1bOGsy9HeNxmNumnOyr96yAgBrKjrIbinsz5t7q4FRzwEGlF0yTEkoFjPZgYOKLYTvkXBm2aqIECmLSDyfIbY4EHN0yfloRQQer0D1OyaQVjfbIpoekykjs5vLTOgDVnP/fUZ8MMjRAdL6WCwiqmDVzoE8NRhbJpbu+Whyq1FlZvyeswIAvgmNNrORrPYhySjN+sA6yDfylobk7jMCZH0cThHlCEJrvI79NB3jRm8Ag178qw4uhDSzNvI1k/8xz23c7oB+pPgCfH8WX+PyTmMNS3SVM6icG8FM1+oFoZOG8/p4gW+zMnUQITHtC2jqlFXpzA0oxSwiB6fThikS7+q/lUzkfSci0K+sM58bjEz3/Z2O3N2CeYID9LE=
  - secure: Bu8J32bGpu/Nx2AshndYHIy9Bvfyu93k4mwtSQh/6S41y73EiW6Ittuo/Yad28SfwlGd1WkAXoke/6rx8rrXtIDhyhemYnX7yLb0dci29Td2PfwfHQ7J/xnxSYgSkd7p+faLy3jIx+UZzV9R4LgZkrHZiULeWgM1RxmKXtbEQDZxHwUjNz9AW6sC3Uh6aKzm8BPzQK0jJvbUx/iG0OnyTSCEofYmuaVvQwXk4lgbvTzChDVm1u2+uHuQcKNZwoLNpDC4PlR1rr85b8jML7lyMbi+PQ9HcX6Hl8JprI10/16qoA3aMhYbHpHec1tL3aPQj7VSSuRMvgmeUADrTy1i6caBLSv6IntpAFaELrySfa78IwQF1O3SvcCgW4knVaafBd98Q+UsrFxLERbyjUuVB26admgBCfoqdUMYexBzu1viTkwe8K8yi6XNd1L+dbp2K2rRS6SzUtfVZdi6jGyZYaPWY6of8b6JzYcUrjf2ZJ/7jhXFgwaOmANFyHxY4sd8MgE2PWkfBM5nbp1xSw9rAF8DKxtyvzinWJy2mBmgS23fs+yZfnOUJl4d2DhQpLEaXo51BJVTnOoMW1en/IP7DZuGDg/qxTgJfFVGWfHhKuSsflauZRktIi2itoLkoArbH8ezOxmKNmcMFz7r9q+FrV5n4QfBgLRvZQkLzVegzt0=
  - secure: WZCigGCFeF34aDxPGr7TCMChXewa2KlORdoKPTK+o96UkrqaqWfsci6eSkQqMfB/6lBaoPRv8Ke0wwLI6cHVoEqURwdbHBVgG4tKTlx3Nk939vheg4BeXKTgGm+vM83FEJxXyVXV56LNtMYsvW2I2angl54tgt1FRi0lu8o0cBYj9WVOdt2gjPwjAb75WU7hhQW9iQ5mYbv6P5Wt9ygTqfNd/cCqpaPAXAovoY0IdXJUGRLih+S8MHUhniQwAzJwehuSxIeUMuWK8elt1A5JjrBGRYedlJhlAinJykjqbqikz/2LlEMv2rqrRhjXKPjAJb5hR6z5Zap0ZvvH4bmihm0J+mWeVMTlgAZyowOUW09XlZSUsilaUo4xTYQ5KfY6cs2xL4UP+AJt65nuIauoPskXH2u1xWtwBg6Of3zkwvISr6muP7QycYc43qqSAX++vbdOOGVrTW7D65p3aZpbxUXOKoTthrn78bFyT0G5E5EH/xT7tanBbHJTQmDwZpwe80LcHMj7zYPsjqJT7pg4ytUoZmJkPzu+JVzAVjREs7t0TNFnqyof8OXpo9V0zC7mwJNibpWXnKmM/ZwzdxIQSAV/RF8k0glT7WeCm0mjlDnCJvWybk79OKIY2/iVchQ12wbzLQLQlpl5NFKUpwBPpdtNXkZ0WWDFAL7wNkwPQVk=
  - secure: lzKHNnm59TBit5xJ08dkr6cN22kffdke09iVPzK0EvEk0Lgf2rRSZDgBJ5VEsejzqKZOrHwiXy7UzwdV7mcTY5J27nwgk33Xy2cFaS9Dc1hnEXPBoUWvG1u2nS8Yg86So+mgeQyvDpwqHfJgg2pB/FCAwilFm/B++9mOKqemZsOrBHEmxUD6n8QyRmDDhLXjMTrsx0ENZwQnfKYClTGfCT7c6/6W8XxHTZmYbN7i3CDTPkRLU+CYTd8O9rhCARDbvMJrueRYdcZk8Jz+018Ko3FPLkfLVmoVzo8fypp8CgBkuiraUkYfCGD3QcJG0UEH10HMdJwtSxxbt7bk1jO/sanEFAc8kG1vC4Mr0UCOiTlqbuBEVuyGHHmnxlAaNg0aaozKoIFZW/af0etrelcjCMmtwf2izIqpdFfcBjd91bGZTbHCsZmBPqsvtoH/pRexqHGsDGhFMxu0cTIHh/EPqhJl2KilPB5KMb7MTiWIOmstXOOrv8GCbwT3FG02j7k0qSsHFbZJXZZaXU3gNNB+vMEoL9YFvykKvQOyn9lb3/R54j0/IG/8UXwKbteUlTbs5shdaJ/L0ffJsb0dOdnykEDOPD9paXjCp7+ENRfS8mbvYNhY1Hk591YzKVgxo1wldZ467ry5GdVXCujWx4Co1g3CBZiD9eyqK1oD9Q8+SSY=
addons:
    apt:
        packages:
            - sshpass
after_success:
#    - tar -czf package.tgz build
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp target/blog.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/blog/blog_deploy.sh