language: java
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
deploy:
  provider: releases
  api_key: "${api_key}"
  file: "./target/blog.war"
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email:
  - teaho2015@gmail.com
  #before_install: #one way to link server test
  #- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  #  -in travis.enc -out travis -d
before_install:
 #- sed -i "s/jdbc\.url=.*/${jdbc_url}/g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.username=.*/${jdbc_username}/g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.password=.*/${jdbc_password}/g" src/main/resources/properties/jdbc.properties
env:
  global:
  - secure: CjuDDI8KOXBk6wv1V93Iop5/9bImsVI0V2GwSmSvE1M5jrOJZpEeFZ0o146i44W2rdgesNzWW8bxJEuh33iUlUR27I/b2HRiwkcEgnuqfiK0lVC7i2wdr9zjSAh9eWdD82uGF6jUP94uJaSRzhMTAPPJhR4i7je5FEFA31c2qeE+9H5v0sQ9F77FD3njNcL58Spsx5i3748iPbqbCv59J4qeJvo4mg5HvvfQYUrE6NEhlk6DdVzwmeMM9o1pzsTIkIyE7dJ2B/3QJbSxIlaWqS658HYt0UMDPp5jBYnk9e7s/WjUUpE57TV2cJ8US5PAe9lQFLbmvA9M0SupsbYtmCv96CJ5E18zkVZkNOuqUmLuYKBg5p5eRWqW6Q4VR0+wllAI/LYcBHuc1doWhnOeYxfU7Z1RVzzsOMqd7NPsnUtQ+hkdUpXPdZyOGvwKZSkKG9dfXx6LUsvLUwOdbGhi1LYCYEKs+pzWLXaDj99Audoep5yVHVpAQ5QkPjT+eBlmwztLptI1w3SpaLWVXe6Z6Pq4JDnl4MTcUw/6YhxJ7Vg2jE7ssrwB6aL8vn4ScdaA1VwS4JVVIGLga7BI14e3WBMt+Lkxaxat4ygJPqBVrHwRrI9vWLdONe0tcdwkQV+M3UViuEDIgPGzzw5GHD8hDkOQ+XYRnVCExaQ5LROePvk=
  - secure: AwRi7hpEobPPItJMI4WFeHMrdNOqFK5K5MInA6HYJlO9Z1pSWUYcDYRuFX1tsNo77pQPPblW3MACQ5EzNMfDQUPSBweO155wLPSYAJTv+fdhhpv7hFz4BaPpZ8h49qeia9YXkBlW02q18t+a/cNryQJdfsZqjYqhL0rcNEZMG2fodefdmr+y33mVFhDiRdtl+6TLeAVYEaZhC+u4gkgb5tmWkkiZicG/b3ZQTSvzRg1HdRo51GEqAfIL3a09i5NgWKbS8KObXxcAa4uTxUpQErOm3CH3twGyJiuNglsyfi3qIydImco75inL92hCXX0aD+cwH+XQ0mbWGKNQbnWrN7BjerEHyV6zfUYfLaZNNnCDRi4aK20yb6tqM9ivYxtR3KI9OY2nWwkebZ/Wi98kkWjkm8FEOgZfV/MmLT7m0jh7QY7mnR3PspD542kbooC6zbLtSJaxNG12AyGwCMP8Pa3/u4Z2Dyez1xP2W6RivLV+kDiBVp/KTMPnB1oa4ZWXCtpCcRouq//7q/7fgPBQEzhqikzhGJpiFa7/ytaJqb6Co7W3b7Y7XPBACp6JrJHkNu/kAyNMwB501BLlCejzPIwTUvgKAFr2vawZPDvHEp/EtDU+gGacfFFyFcLPmucJrUx/AK0A4IoMzg9cDME/B7DfkJKzJhyjZGnoutDpALA=
  - secure: tkJImyr9EuenIGcZzwn/2HjMQfiUtMUdi/THyGsAO3DuC/HuRwjUH29clrG4fFgiqGzSjtYmmEddNc/G3pBnaHx34yVeZ6gGrVLc/4a0sKCyijBmoYLplpGB+D8OtzM5hZ295eo9AR/KaFLRnotA8eFq+7EnkRVx+dEeQYu3DaTIt4WMSvQrwrsmXC2Zz9FvBnkVfyMD+b2WXEA4FJC72jCb9X5GDeArJHd2qb3Pxg9b8SrJ7pTTWShcZ2+l/30/uTQUAFEltvrvHVfruzlpKO1+PYeh1YVMVKkhyb2SpARxShJcO49jM2iZ3B6+96N2JalKp2LM9XOLAKVVwpFyGY2VBXFIOXoQt6GsSQKDhhFPnFM2XGu7llcJnYXIZFxpjjHXi2Yo0i77vBu056ygQp9Jwd3P/7gPBavjP5eMbPwVEX4Yi00AVctAg/rgU193UpCXbJ36aRRpaHph4TlQhduGpyNCwLb73YqlP8LcI6B+Rj8zULv2Y3Baq3JnWTkipF0bOENUI9BvE7HitlIY1EJBQR/nZPNsvd8o25nCLldKm2HX40Ei4UbFcmCKYps6+GwlUZU0t6sOS2t3Cm7yG/AdLAEyFebg/7PZ2voEeGKBYpyOt64TidGlT5JmOhjc1JD0yl6XdfqyhdQ94SuHnIoJRULvAoiK97TQFebHNzI=
  - secure: TO5hTUtLfnOOfgB1KCxDPXKT3mHHBnDtyv7B0a9O2034pt5PptvpqHFp7PvbnGkSbNl4Z4hdvtrF++3GtCeQu/dLtDCiqRUDrar9/te7RwoQ4kN6AJ0+SD6CNcTwK8ZMKm9CJ91lnnkd2uw3Af0xFIydHJAmc0709+yhn2aTP2BFjgSw9Exf0LUKhxO67fJ2jakRzOMalZWg4qAXvPFp23oXnbPBIx3G3Tdrc+/KXKk20ebP0bK5FAjQOYwLLJiGqSYLjEi/Dkp5zlMpjZEaCxYx7Z9CAfygHpzErnLqMBlEQlHn2S3cUo78NUNrXL/5eD/3buKFb0pDM7bKaADUWWw7VlFCj/+u+DNk93id8inuUCQXE/1Cvm/Khqg4/v7dT4KzYf6Tr2mygKNMrWQdmDiRK8J2ExOgJYMdnKohNWESi34yhNq+fJPCql0vvCWzQfkWCH1nlAgkSPa6XxEs9zSp08q5ieQ7jLJJ8Jzfijf6PgmXVxIgVS8sWO71uhfIZgyLQ7OMcEQXzytQd0iLRyJXPom/Sq9zta4KVq3cuQCnvUqo8oiavBk/M3pKCsE2cHtpTcvZuIWdVumvHOV1iF5akGd9j9y0dsdmF1bluMOgUoKLRljC8YjuNIJA2Xi4YGoVY6249xZQz1gzqo6luJlqDBuhFJ/Uo/dtvzYFh78=
addons:
  apt:
    packages:
    - sshpass
  ssh_known_hosts: 45.32.76.154:22
#imported-openssh-key
after_success:
- cat ~/.ssh/known_hosts
- export SSHPASS=$DEPLOY_PASS
#- sshpass -e ssh -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "sh /home/lauchapps/test.sh"
- sshpass -e ssh -vv -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null  $DEPLOY_USER@$DEPLOY_HOST "sh /home/lauchapps/test.sh"
- sshpass -e scp -vvv -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null ./target/blog.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh -vvv -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "sh $DEPLOY_PATH/blog/blog_deploy.sh"
