language: java
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
deploy:
  provider: releases
  api_key: "${api_key}"
  file: "./target/blog.war"
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email:
  - teaho2015@gmail.com
  #before_install: #one way to link server test
  #- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  #  -in travis.enc -out travis -d
before_install:
 #- sed -i "s/jdbc\.url=.*/${jdbc_url}/g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.username=.*/${jdbc_username}/g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.password=.*/${jdbc_password}/g" src/main/resources/properties/jdbc.properties
env:
  global:
  - secure: r7nYfGMstLCsnUr7XFtyqkE8tmEosCJvquSQXO5jlu0fRoHvKe5aFEoA3eP6TDPh9lTJLEabay/km3O/PP3RuhNzr8AP/9bI6zztxpDP1R0TXEuWM9dxqkc4z1KBQHtvtpsNawZGzJYpMKUMTIcLhSxfdDIOvvayrfisl6hWRu8FpM/Zt5c/qij9xmqBXiEn0u2eEdd7dNDpfNB5FASnm+wtGcrpk8kh5Vq8y2AnRa0203lYnH5yZrvgj06Yb78mhciqz4zb83yXCXed+AHxSyqysBjX/lvymmX9WwvWvQ8Jp/SXgEw6ORJUxLkthXnMW1jnjHo5GJHSvugqjkhOxkG75xS3YheXu/0LO0KbSQjCL3FwYBgeBqC6ocpQvreQ35LXebrYaeEm5dC5kCEpkRJ0sNdaj3zVGwnDp5BZ7nFiJBnUOeLESANfrf+09LS237FhCjzzu7gkMcIVHey6CGgbbK6VtMj1EJ79ES1DlkrPgmsQEQIwFQyelT+e8SPQ7Ya3+2fxiUbvkT4dKhoYYMx6wzHBSsCrh3U8ip8HwgZZdL28rF5u+r9K/1QFPJW+jEMmKvZBokUJ2h2Prv11snQpkcH3VzvU6yH51lp4jacgKR0BXJyi6v5MTwNueyYa5iYEnUMfQxEMMfm3aJpRvdeW/DOYTFyrYtp9B66Ej1M=
  - secure: RRRckKhER896kZxUUhuN1z7kYtDlCnDVXUCzyM6t1JbK6T52YpXHK45yXAzpQnZokSYgFqKTGeEqQhXtVI1AGyhepyHfvW0aj2FzBdjholUA1AS/VnIjBwXuI87de8SYSHWzp/a9xLNmchTt+MDraglKVKPH+wNRr22qzA3Ygx0adR++yexMOqPLSnQ2rlLBywww3gfYspIj74TOlZF+oQtN5NK4wQXTPyKGqEKmxWzhS+ZGcVxFb8687bpt0Yf9IN7TlLjXKjF/6lxUNkqDtmg8YfjRII0l5Reqe5MqOS3WPg+WIAHI7SIJRiJ5mdk5DgT99DikvVe3jVWmCvR1joxf5mjV5/dZ+1kZgVnintNsW4KdeaiMia9Yc7BBrJfDyHaNwOkN9QqxYTZWlnVzzuigffq8l0Sqx5sF8O4Q40RRh3cm/FEDnkxIPBRSDPscGem1RhHkQdJUTsQ/UfOeiyLhUrRmAxs57VgB3MaQrSz64nrADfbIYtnsI0zkdIPbREsuQS2Zy7S1I378TKi3lfECJoWa+aXjr/4/a60VomnZNLBYj9vJd2i3bhzUROdyj4TJox5Sa5XTAKxqcBDb5HBsmf14mnClJ9xUsmtXV27gRsLiG+zWRCyDQdNmPZ2Jxqe1A6WhENjBmQrbOUHZPAgpMekBdNry8SzOX22YU1w=
  - secure: ic/UItkP8Ua5pazSaAC9Tx4ElVr0mXAuF4+fWt+Vhq8e23pDd6EofBzdu3w1pCD3FBJeSistGQn+saMj4cW1aU6M/GA85IFaoc/nzPOG6NxV80XGESx1zHp2oIUdLN5BtfNTX0PFZ0ulfm01ZbnWkkjrE//s0HFrY7ORpeV37zxpheoE6X2TiL7TZtkX7CcS+4s9q3g6+vU9YI5Z0pBrqRPlKkHmAYlyQA0vOGbt1e2gxmp3vkDmam5LEqHi+T095p+TiMOWnnnwQJuTpbi3BCFr9qqASSusF1PDBE1Y8BskTe5TAUfwRkcifVN7tpJfJw5o6YBM63UouwicTMUsRadw0HSaaSGipcf5PT9oRKka2LmTtE98Jz+YxzQSR6LGyA2muR4V2XrokXNHFEsPwpSbvMIC2XcQcyPS8Z0laNHT43F0lUobaPG/j8UPJKzfkmi574ksTz9P4tGDJwCZWoItH3Nmo+kMLMB6cnHHQrnOvfl/05wfa9h/bM72iCJgQ/qgOAra9SBG7DZfgAnUFQ25eL8t6WaISmObgukQWg93hPa0/3Eed4zUgNccbKwzwuHe6/ruUhyC6xWgv8bQgo5lE8U/qNUwVg1+6rfCkV15C3vDlKZpXTY0elJLWoA30rxUTxB1Y51BlsLcl8RaiIG21+6ZxfcRPR3xvl9JdLk=
  - secure: iiP4PXjkruLOV7BeMhMmZwueo4mVgmO+/Cc8ZrwwjFb64/Uu2+QgL8kGqEZjTuLqUhQhleMjEOcKFZ6LBDmQ7cKltgjHHAb1hsXgkTD/vW2V4W8EgppMQ9tpJcQ/jE1GHrVQMk+pDwE4K01SXzn30JryzB0YyXGpYi2zj2AIVhbW1pufVtk3LNFFVetDpnQtl/n4ZW6yB8wJJ53cgziB62ovTr46oZ36ujAkFYP7+zMbjg0d0K7bEIC1OYCvvrAIOCa9PZ61pYPPsqL0QgVBv6E3nC2rzgEPvzL+iWyKxvNFgVKjufipNJdGc204wegPoN3qkfvlJYThQTt9co/FGYlCmz+47cF4Pk5230MCj00qVL4bH+21cJdDaZw4w0JcT1xJJlWXYO70W1CQjDkdhUBafKNsR77GQIKZdL6nnqheulIcyq/3qgHvyCE8DA4Bqzrn0l3OyuAU5rRq46RkXXMZ1bu/VGTTSjoSuPg7mI+ICNAdti7VUQBCResYM/pSytniDd8InxthD63OQfTELFO55hJ2uukelH37xP/89sHK37o0XOapfQICawTf5tu4MWlYvJ5qUwyQuz6yin8SQCRFBfFi0dvGy9LJwB+HcLs7rJNnX7FzrkU7tlKlOgEx9NltBP7c4Y71StFM/jd/rvgO44+oJ43lDVjawjopPBY=
addons:
  apt:
    packages:
    - sshpass
  ssh_known_hosts:
  - 45.32.76.154
after_success:
- cat ~/.ssh/known_hosts
- export SSHPASS=$DEPLOY_PASS
#- sshpass -e ssh -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "sh /home/lauchapps/test.sh"
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "sh /home/lauchapps/test.sh"
- sshpass -e scp -vvv -o stricthostkeychecking=no ./target/blog.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST "sh $DEPLOY_PATH/blog/blog_deploy.sh"
