language: java
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
branches:
  only:
  - master
deploy:
  provider: releases
  api_key: "${api_key}"
  file: "./target/blog.war"
  skip_cleanup: true
  on:
    tags: true
    branch: master
notifications:
  email:
  - teaho2015@gmail.com
before_install:
- sed -i "s|jdbc\.url=.*|${jdbc_url}|g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.username=.*/${jdbc_username}/g" src/main/resources/properties/jdbc.properties
- sed -i "s/jdbc\.password=.*/${jdbc_password}/g" src/main/resources/properties/jdbc.properties
addons:
  apt:
    packages:
    - sshpass
after_success:
- cat ~/.ssh/known_hosts
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -vvv -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null ./target/blog.war $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh -vvv -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null  $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/blog_deploy.sh
