server:
  port: 22200
spring:
  application:
    name: blog-server
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blog?autoReconnect=true&rewriteBatchedStatements=true&userUnicode=true&characterEncoding=utf8&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: 2222
    driverClassName: com.mysql.jdbc.Driver
#  mvc:
#    view:
#      prefix:

app:
  pics:
    location: /data/app/blog/static